name: Render & Publish
on:
  push:

permissions: 
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::tidyverse
            any::giscoR
            any::sf
            any::gganimate
            any::gifski
            any::transformr
            any::ggstream

      - name: Publish to GitHub Pages (and render) 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}